version: '3.7'

services:
    mongodb:
        container_name: github_search_mongodb
        image: mongo
        command: ["--bind_ip_all"]
        environment:
            MONGO_INITDB_DATABASE: ${DATABASE_NAME}
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MONGO_INITDB_USERNAME: ${DATABASE_USERNAME}
            MONGO_INITDB_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - ${DATABASE_PORT}:27017
        volumes:
            - ./.docker/mongodb/data/db/:/data/db
            - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d
        networks:
            - db
        restart: always

networks:
    db:
        driver: 'bridge'
